<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head profile="http://gmpg.org/xfn/11">
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<title><?php wp_title( '' ); ?></title>
	<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
	<meta name="viewport" content="width=device-width">
	<!-- Generated by wp_head() - Start -->
	<?php wp_head(); ?>
	<!-- Generated by wp_head() - End -->
</head>
<body <?php body_class(); ?>>